{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyhelper
  version: {{ version|replace("-", "_") }}

source:
  fn: shinyhelper_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinyhelper_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyhelper/shinyhelper_{{ version }}.tar.gz
  sha256: f7ed62543ab4d05a34b69a9183517a09e93e1b2da85b113282de0f9982db90b0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-markdown
    - r-shiny
  run:
    - r-base
    - r-markdown
    - r-shiny

test:
  commands:
    - $R -e "library('shinyhelper')"           # [not win]
    - "\"%R%\" -e \"library('shinyhelper')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyhelper
  license: GPL-3
  summary: Creates a lightweight way to add markdown helpfiles to 'shiny' apps, using modal dialog
    boxes, with no need to observe each help button separately.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
