{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyhelper
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyhelper_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyhelper/shinyhelper_{{ version }}.tar.gz
  sha256: f7ed62543ab4d05a34b69a9183517a09e93e1b2da85b113282de0f9982db90b0

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-markdown
    - r-shiny
  run:
    - r-base
    - r-markdown
    - r-shiny

test:
  commands:
    - $R -e "library('shinyhelper')"           # [not win]
    - "\"%R%\" -e \"library('shinyhelper')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shinyhelper
  license: GPL-3.0-only
  summary: Creates a lightweight way to add markdown helpfiles to 'shiny' apps, using modal dialog
    boxes, with no need to observe each help button separately.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shinyhelper
# Type: Package
# Title: Easily Add Markdown Help Files to 'shiny' App Elements
# Version: 0.3.2
# Authors@R: person("Chris", "Mason-Thom", email = "christopher.w.thom@outlook.com", role=c("aut","cre"))
# BugReports: https://github.com/cwthom/shinyhelper/issues
# Description: Creates a lightweight way to add markdown helpfiles to 'shiny' apps, using modal dialog boxes, with no need to observe each help button separately.
# License: GPL-3
# Imports: shiny, markdown
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-11-09 12:10:41 UTC; chris
# Author: Chris Mason-Thom [aut, cre]
# Maintainer: Chris Mason-Thom <christopher.w.thom@outlook.com>
# Repository: CRAN
# Date/Publication: 2019-11-09 12:30:02 UTC
