appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OmCogjglyPwP4qXr6nrjNC2ZdvOTXTnX0gYPGqX7TutAw5DXWErcTVkCMFdNpkEQrep9SHLo4J7uv22V+TEgOB8TxtKeguFZZuTIdj/9mmusmG0k5epUEtWgOto1pcQONamqY4Y4xixu1kiilhAgzfGp1ngMqInQd4mdUnUKlRJOdFK7/8dBkjGqkMGSiZ5ntOarQXoi1vCH5SHRw0xjJ2vVPdi6CpimG4gJJOhjsD8Kh34MO0ix6rQ6F0cAnYwtOCqCc59ZY67LeSkeoFWeY+2aPcJ64lYL5PWdQvS8vONCcCRS4xzI5qMyLIh/5Ajyw7jhcTF5wQaUoOo8o7rFxfqfbeuclPv+tidtpri8dgHfCZjjAsyKtdBKG8qbKAf6Nerl2jvi3L5rTfUL1sRQrHUoKl5qMIPSgq08XthYjll8m6pbqo7kKQZBhl6WL+53NBgxozdLqzjZBScCPro5S8N9tFmONwtJJZ/gDeMY70120JDps2qbj/+r813Qy8W/n9HdkjnNMZAfMfhgsCIjp6d99SQM8WXUgIhpdIKk+URZvcGkrrtvNf8H0N7zz++OnJuy37dSZXwuFDWzp2uZbzQr1NznoeCTYqiVT5DNL9vbP/L7+wVd74H6PM54ADI5zgOVjwpRRpu2pxjDTgd5mlQTCDo+RR2qYwhVX/pkTIk=}
bot:
  automerge: true
